server:
  port: 8081
  servlet:
    context-path: /order

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/projects?currentSchema=order
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    command:
      topic: order-command-topic
    services:
      product:
        command:
          topic: product-command-topic
      payment:
        command:
          topic: payment-command-topic